bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: h35DRATUT0dXk3YWZ1/AUd6aUa43w59yQi07lKZYotlv8AMWQzEXxwUGddI/g4XN9hMBHsgeoBPbqfUxh8QlVPcRC+ci370/XHzPlk/sl17yVdSTjOU7DLiMdV3KLvT9D1bXO/2b6v7cMX07BdybM1tQ2L+7gK6xObYvYDdtqH8qFrBxLx9STLbbVsUPT8S0PgisD2P0L55F2kndB7mqkcySv8M7/wGR55PqGnvXLFgHhxp8qrsgeJwFJ4P1QHLpaEGxiXWSETRpJcpiAjLJtB1AQ42eZSqDYEOcwQLY494A0kZlnzN7nqRm4+9GtS+3dnzVAF1pGKQ4H/pK534rW6RbvlESE3raG0lhJh76748+WWUIqfd9UKJfyVLSRFNuYGyU84M+OaxPC7gGLMe3Bi+yXQ5Hngro8ak6/Qz/alTdnCM2jpZxHGkLQldn0lzDs4QNhr+auOMNnD1GiSy7Wlko1pY25sxYLMh/qvS5FYA09klEDS4pVaBah8szl5Aoy/o/gMBW5kNsOek5N8nl2bGfujr945ItLg2HTEkskwsnVYuVJzqqenlshDzCxDyvJIYatefZFhSYnZ68Jy06pd9wegQ25+U+HdXRA5Rbtf7uwQqP+5Uwobq5DOSigvVi96njSAeGUWWTLWdgGlZ/ZcVCNLMpN46937vCWI7fSIg=
conda_forge_output_validation: true
